import assert from "node:assert/strict";
import { EventSchema } from "@musubi/types";
import { resolveEventTimeEdit } from "@musubi/calendar";
import { graphRecurrenceForEvent } from "./microsoft_recurrence";
const event = EventSchema.parse({ id: "00000000-0000-4000-8000-000000000181", revision: 1, creatorID: "owner", organizer: "", title: "Pattern", color: "red", calendars: [], isCanceled: false, recurrence: "RRULE:FREQ=DAILY;COUNT=4", ...resolveEventTimeEdit({ kind: "zoned", timeZone: "Europe/Prague", startLocal: "2026-03-02T09:00:00", endLocal: "2026-03-02T10:00:00" }) });
const convert = (recurrence: string) => graphRecurrenceForEvent({ ...event, recurrence });
assert.deepEqual(convert("FREQ=DAILY;INTERVAL=2;COUNT=4"), { pattern: { type: "daily", interval: 2 }, range: { type: "numbered", startDate: "2026-03-02", recurrenceTimeZone: "Europe/Prague", numberOfOccurrences: 4 } });
assert.deepEqual(convert("FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,WE").pattern, { type: "weekly", interval: 2, daysOfWeek: ["monday", "wednesday"], firstDayOfWeek: "monday" });
assert.equal(convert("FREQ=WEEKLY;WKST=SU").pattern.firstDayOfWeek, "sunday");
assert.deepEqual(convert("FREQ=MONTHLY;BYMONTHDAY=2").pattern, { type: "absoluteMonthly", interval: 1, dayOfMonth: 2 });
assert.deepEqual(convert("FREQ=MONTHLY;BYDAY=1MO").pattern, { type: "relativeMonthly", interval: 1, daysOfWeek: ["monday"], index: "first" });
assert.deepEqual(convert("FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1").pattern, convert("FREQ=MONTHLY;BYDAY=1MO").pattern);
assert.deepEqual(convert("FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=2").pattern, { type: "absoluteYearly", interval: 1, dayOfMonth: 2, month: 3 });
assert.deepEqual(convert("FREQ=YEARLY;BYMONTH=3;BYDAY=1MO").pattern, { type: "relativeYearly", interval: 1, daysOfWeek: ["monday"], index: "first", month: 3 });
assert.equal(convert("FREQ=DAILY;UNTIL=20260329T065959Z").range.endDate, "2026-03-28");
assert.equal(convert("FREQ=DAILY;UNTIL=20260329T070000Z").range.endDate, "2026-03-29");
assert.equal(convert("FREQ=DAILY;UNTIL=20260328T230000Z").range.endDate, "2026-03-28");
const allDay = { ...event, ...resolveEventTimeEdit({ kind: "all-day", startDate: "2026-03-02", endDate: "2026-03-02" }), recurrence: "FREQ=DAILY;UNTIL=20260310" };
assert.deepEqual(graphRecurrenceForEvent(allDay).range, { type: "endDate", startDate: "2026-03-02", endDate: "2026-03-10" });
for (const recurrence of ["FREQ=YEARLY;BYMONTHDAY=2;COUNT=4", "FREQ=YEARLY;BYDAY=1MO", "FREQ=HOURLY", "FREQ=DAILY;BYHOUR=9", "FREQ=DAILY;COUNT=2;UNTIL=20260330T070000Z", "FREQ=DAILY;COUNT=0", "FREQ=DAILY;INTERVAL=2147483648", "FREQ=DAILY;COUNT=2;COUNT=3", "FREQ=DAILY\nEXDATE:20260303T080000Z", "FREQ=WEEKLY;BYDAY=TU", "FREQ=MONTHLY;BYDAY=MO,TU;BYSETPOS=1", "FREQ=MONTHLY;BYDAY=5MO", "FREQ=MONTHLY;BYDAY=1MO;BYSETPOS=1", "FREQ=MONTHLY;BYMONTHDAY=-1", "FREQ=YEARLY;BYMONTH=4", "FREQ=DAILY;UNTIL=20260230T080000Z", "FREQ=DAILY;UNTIL=20260301T080000Z"]) assert.throws(() => convert(recurrence));
assert.throws(() => graphRecurrenceForEvent({ ...event, ...resolveEventTimeEdit({ kind: "floating", startLocal: "2026-03-02T09:00:00", endLocal: "2026-03-02T10:00:00" }) }), /explicit/);
assert.throws(() => graphRecurrenceForEvent({ ...event, ...resolveEventTimeEdit({ kind: "zoned", timeZone: "Europe/Prague", startLocal: "2026-03-31T09:00:00", endLocal: "2026-03-31T10:00:00" }), recurrence: "FREQ=MONTHLY" }), /Month-end/);
console.log("Graph recurrence candidates: six patterns, COUNT/UNTIL, week boundaries and explicit lossless refusals: OK");
