import assert from "node:assert/strict";
import ICAL from "ical.js";
import { googleEventState, microsoftEventState, caldavEventState } from "./provider_event_state";
const google = googleEventState({ organizer: { email: "organizer@example.test", self: false }, attendeesOmitted: true, attendees: [{ email: "me@example.test", self: true, optional: true, responseStatus: "tentative" }, { email: "room@example.test", resource: true, responseStatus: "provider-new-response" }], reminders: { useDefault: false, overrides: [{ method: "popup", minutes: 15 }, { method: "provider-new-method", minutes: 25 }] }, transparency: "opaque", visibility: "private", status: "confirmed", eventType: "focusTime", conferenceData: { entryPoints: [{ uri: "https://meet.example.test/join" }] } });
assert.equal(google.isOrganizer, false);
assert.equal(google.ownResponse, "tentative");
assert.equal(google.attendeesComplete, false);
assert.equal(google.attendees[1]!.response, "provider-new-response");
assert.equal(google.eventType, "focusTime");
assert.deepEqual(google.reminders, { provider: "google", useDefault: false, overrides: [{ method: "popup", minutes: 15 }, { method: "provider-new-method", minutes: 25 }] });
assert.equal(googleEventState({ attendees: [{ self: true, responseStatus: "accepted" }, { self: true, responseStatus: "declined" }] }).ownResponse, null);
const graph = microsoftEventState({ isOrganizer: false, organizer: { emailAddress: { address: "owner@example.test", name: "Owner" } }, responseStatus: { response: "notResponded" }, attendees: [{ emailAddress: { address: "guest@example.test" }, type: "optional", status: { response: "accepted" } }], isReminderOn: true, reminderMinutesBeforeStart: 20, showAs: "workingElsewhere", sensitivity: "confidential", type: "exception", onlineMeeting: { joinUrl: "https://teams.example.test/join" } });
assert.equal(graph.ownResponse, "notResponded");
assert.equal(graph.availability, "workingElsewhere");
assert.equal(graph.privacy, "confidential");
assert.equal(graph.attendees[0]!.self, null, "account email matching is not guessed");
assert.equal(microsoftEventState({}).attendeesComplete, false);
const resource = "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:meeting\r\nDTSTART:20260908T090000Z\r\nORGANIZER;CN=Owner:mailto:owner@example.test\r\nATTENDEE;ROLE=OPT-PARTICIPANT;PARTSTAT=TENTATIVE;CN=Guest:mailto:guest@example.test\r\nCLASS:PRIVATE\r\nTRANSP:TRANSPARENT\r\nSTATUS:TENTATIVE\r\nBEGIN:VALARM\r\nACTION:AUDIO\r\nTRIGGER;RELATED=END:-PT15M\r\nREPEAT:3\r\nDURATION:PT5M\r\nX-UNKNOWN:keep\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n";
const caldav = caldavEventState(new ICAL.Component(ICAL.parse(resource)).getFirstSubcomponent("vevent")!);
assert.equal(caldav.ownResponse, null);
assert.equal(caldav.isOrganizer, null);
assert.equal(caldav.attendees[0]!.role, "OPT-PARTICIPANT");
assert.deepEqual(caldav.reminders, { provider: "caldav", alarms: [{ action: "AUDIO", trigger: "-PT15M", related: "END", repeat: "3", duration: "PT5M" }] });
assert.equal(caldav.privacy, "PRIVATE");
assert.ok(resource.includes("X-UNKNOWN:keep\r\n"), "read never rewrites the provider resource");
console.log("Provider state reads: own response evidence, participant roles, native reminders and richer privacy/availability: OK");
