import {
  themeTokenCssVariables,
  themeTokens,
  type ThemeScheme,
  type ThemeTokenName,
} from "./theme-tokens";

const GENERATED_FILE_HEADER =
  "/* This file is generated by pnpm --filter @musubi/design-system generate. */";

function renderThemeBlock(selector: string, scheme: ThemeScheme): string {
  const declarations = (Object.keys(themeTokenCssVariables) as ThemeTokenName[])
    .map(
      (name) =>
        `  ${themeTokenCssVariables[name]}: ${themeTokens[scheme][name]};`,
    )
    .join("\n");

  return `${selector} {\n  color-scheme: ${scheme};\n${declarations}\n}`;
}

export function renderThemeTokensCss(): string {
  return [
    GENERATED_FILE_HEADER,
    renderThemeBlock(":root", "light"),
    renderThemeBlock(':root[data-theme="dark"]', "dark"),
    "",
  ].join("\n\n");
}
