import {
  themeTokenCssVariables,
  themeTokens,
  type ThemeScheme,
  type ThemeTokenName,
} from "./theme-tokens";
import {
  componentDimensions,
  controlHeights,
  motionDurations,
  radii,
  spacing,
  typeSizes,
  type MotionRole,
  type RadiusName,
  type SpacingStep,
  type TypeSize,
} from "./foundation-tokens";

const GENERATED_FILE_HEADER =
  "/* This file is generated by pnpm --filter @musubi/design-system generate. */";

function renderThemeBlock(selector: string, scheme: ThemeScheme): string {
  const declarations = (Object.keys(themeTokenCssVariables) as ThemeTokenName[])
    .map(
      (name) =>
        `  ${themeTokenCssVariables[name]}: ${themeTokens[scheme][name]};`,
    )
    .join("\n");

  return `${selector} {\n  color-scheme: ${scheme};\n${declarations}\n}`;
}

export function renderThemeTokensCss(): string {
  return [
    GENERATED_FILE_HEADER,
    renderThemeBlock(":root", "light"),
    renderThemeBlock(':root[data-theme="dark"]', "dark"),
    "",
  ].join("\n\n");
}

const typeSizeCssVariables = Object.fromEntries(
  Object.keys(typeSizes).map((size) => [size, `--text-${size}`]),
) as Record<`${TypeSize}`, `--text-${TypeSize}`>;

const spacingCssVariables = Object.fromEntries(
  Object.keys(spacing).map((step) => [step, `--space-${step}`]),
) as Record<`${SpacingStep}`, `--space-${SpacingStep}`>;

const radiusCssVariables = {
  sm: "--radius-sm",
  md: "--radius-md",
  lg: "--radius-lg",
  pill: "--radius-pill",
  sheet: "--radius-sheet",
  card: "--radius-card",
  control: "--radius-control",
  chip: "--radius-chip",
} as const satisfies Record<RadiusName, `--${string}`>;

function rem(size: number): string {
  return `${Number((size / 16).toFixed(4))}rem`;
}

function renderFoundationBlock(): string {
  const declarations = [
    ...(Object.entries(typeSizes) as Array<[`${TypeSize}`, number]>).map(
      ([size, value]) => `  ${typeSizeCssVariables[size]}: ${rem(value)};`,
    ),
    ...(Object.entries(spacing) as Array<[`${SpacingStep}`, number]>).map(
      ([step, value]) => `  ${spacingCssVariables[step]}: ${value}px;`,
    ),
    ...(Object.keys(radii) as RadiusName[]).map(
      (name) => `  ${radiusCssVariables[name]}: ${radii[name]}px;`,
    ),
    `  --row-min-height: ${componentDimensions.rowMinHeight}px;`,
    `  --control-height: ${controlHeights.pointer.control}px;`,
    `  --compact-control-height: ${controlHeights.pointer.compact}px;`,
    ...(Object.keys(motionDurations.web) as MotionRole[]).map(
      (role) => `  --motion-${role}: ${motionDurations.web[role]}ms;`,
    ),
  ].join("\n");

  return `:root {\n${declarations}\n}`;
}

function renderTouchFoundationBlock(): string {
  return [
    "@media (max-width: 599px) {",
    "  :root {",
    `    --control-height: ${controlHeights.touch.control}px;`,
    `    --compact-control-height: ${controlHeights.touch.compact}px;`,
    "  }",
    "}",
  ].join("\n");
}

export function renderFoundationTokensCss(): string {
  return [
    GENERATED_FILE_HEADER,
    renderFoundationBlock(),
    renderTouchFoundationBlock(),
    "",
  ].join("\n\n");
}
