import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import { config } from "@musubi/config";
import { account, db, user, beginAvailabilityDiscovery, reconcileAvailabilitySources, listAvailabilitySources, setAvailabilitySelection, readAvailabilitySources, removeExternalAccountData, getUserExternalCalendars, markOAuthAccountReconnectRequired } from "@musubi/db";
import { GOOGLE_AVAILABILITY_SCOPE } from "@musubi/types";
import { googleAdapter } from "./adapters/google";
import { syncProvider } from "./engine";
import { readGoogleAvailability } from "./google_availability";
async function main() {
  assert.equal(process.env.ENVIRONMENT, "test", "Use a disposable integration-test database");
  const owner = randomUUID(), other = randomUUID(), accountID = randomUUID();
  const oldFlag = config.api.googleAvailabilityEnabled;
  config.api.googleAvailabilityEnabled = true;
  const originalFetch = globalThis.fetch;
  let role = "owner", mode = "busy", reads = 0, invalidDiscovery = false;
  let onRead: (() => Promise<void>) | undefined;
  const range = { start: "2026-10-25T00:00:00Z", end: "2026-10-26T00:00:00Z" };
  globalThis.fetch = async (input, init) => {
    const url = new URL(String(input)); assert.equal(url.hostname, "www.googleapis.com", "No live provider calls");
    if (url.pathname.endsWith("/calendarList") && invalidDiscovery) return Response.json({});
    if (url.pathname.endsWith("/calendarList")) return Response.json({ items: [{ id: "source", summary: "Private calendar label", backgroundColor: "#7A8BA3", accessRole: role }] });
    if (url.pathname.endsWith("/events")) return Response.json({ items: [{ id: "event", etag: '"e1"', summary: "Private appointment", description: "Private notes", status: "confirmed", start: { dateTime: "2026-10-25T09:00:00Z", timeZone: "UTC" }, end: { dateTime: "2026-10-25T10:00:00Z", timeZone: "UTC" } }], nextSyncToken: "cursor" });
    assert.equal(url.pathname, "/calendar/v3/freeBusy"); assert.equal(init?.method, "POST"); reads++;
    const action = onRead; onRead = undefined; if (action) await action();
    return Response.json({ kind: "calendar#freeBusy", timeMin: range.start, timeMax: range.end, calendars: { source: mode === "error" ? { errors: [{ reason: "notFound" }] } : { busy: mode === "empty" ? [] : [{ start: "2026-10-25T09:00:00Z", end: "2026-10-25T10:00:00Z" }] } } });
  };
  try {
    await db.insert(user).values([{ id: owner, name: "Owner", email: `${owner}@example.test` }, { id: other, name: "Other", email: `${other}@example.test` }]);
    await db.insert(account).values({ id: accountID, userId: owner, providerId: "google", accountId: "native", refreshToken: "fixture", accessToken: "fixture", accessTokenExpiresAt: new Date(Date.now() + 3600000), scope: `https://www.googleapis.com/auth/calendar.events ${GOOGLE_AVAILABILITY_SCOPE}` });
    await syncProvider(googleAdapter, owner, { id: "native", label: "Fixture account" });
    assert.equal((await getUserExternalCalendars("google", owner, "native")).length, 1);
    role = "freeBusyReader";
    await syncProvider(googleAdapter, owner, { id: "native", label: "Fixture account" });
    assert.equal((await getUserExternalCalendars("google", owner, "native")).length, 0, "Downgrade still removes the detail mirror");
    let [source] = await listAvailabilitySources(owner); assert.ok(source); assert.equal(source.enabled, false);
    assert.deepEqual(await listAvailabilitySources(other), []);
    await assert.rejects(setAvailabilitySelection(other, source.id, { enabled: true, expectedGeneration: source.generation }));
    await assert.rejects(readGoogleAvailability(owner, { ...range, sourceIds: [source.id] }), "Disabled sources cannot be read");
    await setAvailabilitySelection(owner, source.id, { enabled: true, expectedGeneration: source.generation });
    const request = { ...range, sourceIds: [source.id] };
    const good = await readGoogleAvailability(owner, request); assert.equal(good.sources[0].status, "available"); assert.equal(JSON.stringify(good).includes("Private"), false);
    await assert.rejects(readGoogleAvailability(other, request));
    await markOAuthAccountReconnectRequired(owner, "google", "native", "invalid_grant");
    assert.equal((await listAvailabilitySources(owner))[0].reconnectRequired, true, "Invalid grant retains the reconnect action after clearing its token");
    assert.equal((await readGoogleAvailability(owner, request)).sources[0].status, "reconnect-required");
    [source] = await listAvailabilitySources(owner);
    await setAvailabilitySelection(owner, source.id, { enabled: false, expectedGeneration: source.generation });
    await db.update(account).set({ refreshToken: "fixture", accessToken: "fixture", accessTokenExpiresAt: new Date(Date.now() + 3600000), syncStatus: "active" }).where(eq(account.id, accountID));
    [source] = await listAvailabilitySources(owner);
    await setAvailabilitySelection(owner, source.id, { enabled: true, expectedGeneration: source.generation });
    mode = "error"; assert.equal((await readGoogleAvailability(owner, request)).sources[0].status, "unavailable");
    mode = "empty"; assert.deepEqual((await readGoogleAvailability(owner, request)).sources[0], { sourceId: source.id, generation: source.generation + 1, status: "available", intervals: [] });
    await db.update(account).set({ scope: "https://www.googleapis.com/auth/calendar.events" }).where(eq(account.id, accountID));
    const before = reads; assert.equal((await readGoogleAvailability(owner, request)).sources[0].status, "reconnect-required"); assert.equal(reads, before);
    await db.update(account).set({ scope: `https://www.googleapis.com/auth/calendar.events ${GOOGLE_AVAILABILITY_SCOPE}` }).where(eq(account.id, accountID));
    onRead = async () => { await db.update(account).set({ scope: "https://www.googleapis.com/auth/calendar.events" }).where(eq(account.id, accountID)); };
    assert.equal((await readGoogleAvailability(owner, request)).sources[0].status, "reconnect-required", "A scope revoked during the read cannot disclose intervals");
    await db.update(account).set({ scope: GOOGLE_AVAILABILITY_SCOPE }).where(eq(account.id, accountID));
    invalidDiscovery = true;
    await assert.rejects(syncProvider(googleAdapter, owner, { id: "native", label: "Fixture account" }));
    invalidDiscovery = false;
    assert.equal((await listAvailabilitySources(owner))[0].enabled, true, "Incomplete discovery preserves explicit selection");
    [source] = await listAvailabilitySources(owner);
    onRead = async () => { await setAvailabilitySelection(owner, source.id, { enabled: false, expectedGeneration: source.generation }); };
    assert.equal((await readGoogleAvailability(owner, request)).sources[0].status, "unavailable", "Disable during fetch retires its intervals");
    [source] = await listAvailabilitySources(owner); await setAvailabilitySelection(owner, source.id, { enabled: true, expectedGeneration: source.generation });
    onRead = async () => { const context = await beginAvailabilityDiscovery(owner, "native"); await reconcileAvailabilitySources(owner, context!, [], "Fixture"); };
    assert.equal((await readGoogleAvailability(owner, request)).sources[0].status, "unavailable", "Complete discovery removal retires in-flight intervals");
    const first = await beginAvailabilityDiscovery(owner, "native"), second = await beginAvailabilityDiscovery(owner, "native");
    assert.equal(await reconcileAvailabilitySources(owner, first!, [{ externalId: "source", name: "Old" }], "Fixture"), false);
    assert.equal(await reconcileAvailabilitySources(owner, second!, [{ externalId: "source", name: "Fresh" }], "Fixture"), true);
    [source] = await listAvailabilitySources(owner); assert.equal(source.enabled, false); await setAvailabilitySelection(owner, source.id, { enabled: true, expectedGeneration: source.generation });
    await db.insert(account).values({ id: randomUUID(), userId: owner, providerId: "google", accountId: "second", refreshToken: "fixture", scope: GOOGLE_AVAILABILITY_SCOPE });
    const secondAccount = await beginAvailabilityDiscovery(owner, "second");
    await reconcileAvailabilitySources(owner, secondAccount!, [{ externalId: "second-source", name: "Second account" }], "Second");
    const secondSource = (await listAvailabilitySources(owner)).find(item => item.label === "Second account")!;
    assert.equal(secondSource.enabled, false);
    await assert.rejects(readGoogleAvailability(owner, { ...range, sourceIds: [secondSource.id] }));
    const stale = await beginAvailabilityDiscovery(owner, "native");
    onRead = async () => { await removeExternalAccountData("google", owner, "native"); };
    assert.equal((await readGoogleAvailability(owner, request)).sources[0].status, "unavailable", "Disconnect retires an in-flight reply");
    const fresh = await beginAvailabilityDiscovery(owner, "native");
    assert.equal(await reconcileAvailabilitySources(owner, stale!, [{ externalId: "source", name: "Stale reconnect" }], "Fixture"), false, "Account-generation ABA cannot revive prior discovery");
    assert.equal(await reconcileAvailabilitySources(owner, fresh!, [], "Fixture"), true);
    assert.deepEqual((await readAvailabilitySources(owner)).map(row => row.source.id), [secondSource.id], "Disconnecting one account preserves only the other account sources");
    config.api.googleAvailabilityEnabled = false; await assert.rejects(readGoogleAvailability(owner, request));
    console.log("Google availability DB: detail downgrade retirement, owner isolation, explicit selection, errors, scope, generation, removal and disconnect races OK");
  } finally { globalThis.fetch = originalFetch; config.api.googleAvailabilityEnabled = oldFlag; await db.delete(user).where(eq(user.id, owner)); await db.delete(user).where(eq(user.id, other)); }
}
main().then(() => process.exit(0), error => { console.error(error); process.exit(1); });
